rpm2img: use openssl to generate HMAC
The `sha512hmac` tool from libkcapi requires the kernel to be built
with CRYPTO_USER support. If this dependency is not satisfied, the
signature generation fails with this message:
  Error: Netlink error: sendmsg failed
  Error: NETLINK_CRYPTO: cannot obtain cipher information for hmac(sha512)

Generate the HMAC with `openssl` instead, which does not require any
specific kernel functionality.

Signed-off-by: Ben Cressey <bcressey@amazon.com>